[2024-08-02T21:06:46.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T21:06:46.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:06:24.381157+00:00 [queued]>
[2024-08-02T21:06:46.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:06:24.381157+00:00 [queued]>
[2024-08-02T21:06:46.670+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-02T21:06:46.696+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): saving_top_post> on 2024-08-02 21:06:24.381157+00:00
[2024-08-02T21:06:46.701+0000] {standard_task_runner.py:64} INFO - Started process 1776 to run task
[2024-08-02T21:06:46.703+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_dag', 'saving_top_post', 'manual__2024-08-02T21:06:24.381157+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpfwxooxwj']
[2024-08-02T21:06:46.704+0000] {standard_task_runner.py:91} INFO - Job 254: Subtask saving_top_post
[2024-08-02T21:06:46.758+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_dag.saving_top_post manual__2024-08-02T21:06:24.381157+00:00 [running]> on host 7df8ffa41b22
[2024-08-02T21:06:46.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_dag' AIRFLOW_CTX_TASK_ID='saving_top_post' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T21:06:24.381157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T21:06:24.381157+00:00'
[2024-08-02T21:06:46.854+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T21:06:46.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T21:06:46.876+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project_dag.py", line 143, in saveTopVoted
    f.write(f"{post['title']} {post['text']}")
               ~~~~^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 758, in __getitem__
    raise TypeError("index %r cannot be applied to Cursor instances" % index)
TypeError: index 'title' cannot be applied to Cursor instances
[2024-08-02T21:06:46.889+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_dag, task_id=saving_top_post, run_id=manual__2024-08-02T21:06:24.381157+00:00, execution_date=20240802T210624, start_date=20240802T210646, end_date=20240802T210646
[2024-08-02T21:06:46.915+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 254 for task saving_top_post (index 'title' cannot be applied to Cursor instances; 1776)
[2024-08-02T21:06:46.956+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T21:06:46.984+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T21:06:47.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
