[2024-08-02T18:19:04.559+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T18:19:04.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_dag.send_email manual__2024-08-02T18:18:43.464034+00:00 [queued]>
[2024-08-02T18:19:04.600+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_dag.send_email manual__2024-08-02T18:18:43.464034+00:00 [queued]>
[2024-08-02T18:19:04.601+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-02T18:19:04.630+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email> on 2024-08-02 18:18:43.464034+00:00
[2024-08-02T18:19:04.634+0000] {standard_task_runner.py:64} INFO - Started process 667 to run task
[2024-08-02T18:19:04.635+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_dag', 'send_email', 'manual__2024-08-02T18:18:43.464034+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmppd_lmsgu']
[2024-08-02T18:19:04.636+0000] {standard_task_runner.py:91} INFO - Job 239: Subtask send_email
[2024-08-02T18:19:04.698+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_dag.send_email manual__2024-08-02T18:18:43.464034+00:00 [running]> on host 7df8ffa41b22
[2024-08-02T18:19:04.799+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T18:18:43.464034+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T18:18:43.464034+00:00'
[2024-08-02T18:19:04.800+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T18:19:04.825+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-08-02T18:19:04.825+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-08-02T18:19:06.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T18:19:06.384+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.12/smtplib.py", line 716, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
[2024-08-02T18:19:06.394+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_dag, task_id=send_email, run_id=manual__2024-08-02T18:18:43.464034+00:00, execution_date=20240802T181843, start_date=20240802T181904, end_date=20240802T181906
[2024-08-02T18:19:06.425+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 239 for task send_email (SMTP AUTH extension not supported by server.; 667)
[2024-08-02T18:19:06.454+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T18:19:06.474+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T18:19:06.475+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
